apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-consumer-deployment
  namespace: rabbitmq-ns
spec:
  replicas: 2  # Assuming you want 2 replicas for the consumer
  selector:
    matchLabels:
      app: rabbitmq-consumer
  template:
    metadata:
      labels:
        app: rabbitmq-consumer
    spec:
      containers:
      - name: consumer
        image: <your-registry-path>/rabbitmq-consumer
